---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
    - 10.0.0.100/32

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: k8s-cluster
  namespace: metallb-system
