---

# Run only once from a master node
- name: Init kubernetes masters
  hosts: masters
  become: true
  tasks:
    - name: Initialize the cluster
      ansible.builtin.shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: "/home/{{ node_user }}"
        creates: cluster_initialized.txt

    - name: Create .kube directory
      become: true
      become_user: "{{ node_user }}"
      ansible.builtin.file:
        path: "/home/{{ node_user }}/.kube"
        state: directory
        mode: "0755"

    - name: Copy admin.conf to user's kube config
      ansible.builtin.copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ node_user }}/.kube/config"
        remote_src: true
        owner: "{{ node_user }}"
        mode: "0644"

    - name: Install Pod network (flannel)
      become_user: "{{ node_user }}"
      ansible.builtin.shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: "/home/{{ node_user }}"
        creates: pod_network_setup.txt
