- name: Get masters join token
  hosts: masters
  become: true
  tasks:
    - name: Get join command
      ansible.builtin.command: kubeadm token create --print-join-command
      register: join_command_raw
      changed_when: false

    - name: Set join command
      ansible.builtin.set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- name: Join workers
  hosts: workers
  become: true
  tasks:
    - name: Join cluster
      ansible.builtin.shell: "{{ hostvars['k8s-m1'].join_command }} >> node_joined.log"
      args:
        chdir: "/home/{{ node_user }}"
        creates: node_joined.log
